name: "ctc_postprocessing"
backend: "python"
max_batch_size: 0

input [
  {
    name: "token_ids"
    data_type: TYPE_INT64
    dims: [-1, -1]
  },
  {
    name: "token_ids_lengths"
    data_type: TYPE_INT64
    dims: [-1]
  }
]

output [
  {
    name: "texts"
    data_type: TYPE_STRING
    dims: [-1]
  }
]

instance_group [{ kind: KIND_CPU }]

