name: "ctc_encoder_onnx"
platform: "onnxruntime_onnx"
max_batch_size: 0

input [
  {
    name: "features"
    data_type: TYPE_FP16
    dims: [-1, 64, -1]
  },
  {
    name: "feature_lengths"
    data_type: TYPE_INT64
    dims: [-1]
  }
]

output [
  {
    name: "token_ids"
    data_type: TYPE_INT64
    dims: [-1, -1]
  },
  {
    name: "token_ids_lengths"
    data_type: TYPE_INT64
    dims: [-1]
  }
]

instance_group [{ kind: KIND_GPU }]

parameters { key: "cudnn_conv_algo_search" value: { string_value: "1"} }
