name: "gigaam_encoder_trt"
platform: "tensorrt_plan"
max_batch_size: 0

input [
  {
    name: "audio_signal"
    data_type: TYPE_FP32
    dims: [-1, 64, -1]
  },
  {
    name: "length"
    data_type: TYPE_INT64
    dims: [-1]
  }
]

output [
  {
    name: "encoded"
    data_type: TYPE_FP32
    dims: [-1, 768, -1]
  },
  {
    name: "encoded_len"
    data_type: TYPE_INT32
    dims: [-1]
  }
]

instance_group [{ kind: KIND_GPU }]
